setInterval(() => {
  console.log("Har 2 second baad"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript")
// ≈ 45 characters

}, .00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001);
while(true){
  console.log("Har 2 second baad"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript"+"my name is aqeel and i am learning javascript")
    
}

